import React from 'react';
import { useParams, Link } from 'react-router-dom';
import { useSubmissionPoll } from '../../hooks/useSubmissionPoll';
import { 
  Trophy, 
  Target, 
  Brain, 
  ChevronRight, 
  CheckCircle2, 
  XCircle, 
  AlertCircle,
  Clock,
  ArrowLeft,
  ClipboardList,
  ExternalLink,
  BookOpen,
  ArrowUpRight
} from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import SimulationLoadingScreen from '../../components/SimulationLoadingScreen';
import KpiBeforeAfterTable from '../../components/candidate/KpiBeforeAfterTable';
import DecisionTimeline from '../../components/candidate/DecisionTimeline';
import { SubmissionStatus } from '../../types';

const ResultPage = () => {
  const { id: rawId } = useParams();
  const id = rawId?.replace(/\/c$/, ''); // Sanitize ID if trailing /c was appended
  const { submission, loading, error } = useSubmissionPoll(id || null);

  if (loading || !submission || submission.status === SubmissionStatus.PENDING || submission.status === SubmissionStatus.SIMULATING) {
    return <SimulationLoadingScreen companyName={submission?.scenario?.companyName || 'the company'} />;
  }

  if (submission.status === SubmissionStatus.FAILED) {
    return (
      <div className="h-screen flex flex-col items-center justify-center p-8 space-y-6">
        <XCircle className="text-brand-red" size={64} />
        <h2 className="text-2xl font-bold">Simulation Failed</h2>
        <p className="text-white/40 text-center max-w-md">We encountered an error while running the digital twin simulation. This might be due to a timeout or invalid response format.</p>
        <Link to="/submissions" className="px-8 py-3 bg-white/5 border border-white/10 rounded-xl hover:bg-white/10 transition-all font-bold">
           Return to History
        </Link>
      </div>
    );
  }

  const { evaluation, simulationRun, scenario } = submission;
  
  if (!evaluation) {
    return (
      <div className="h-screen flex flex-col items-center justify-center p-8 space-y-6">
        <AlertCircle className="text-yellow-500" size={64} />
        <h2 className="text-2xl font-bold">Evaluation Incomplete</h2>
        <p className="text-white/40 text-center max-w-md">
          The simulation reported as complete, but your quantitative analysis record is currently empty. 
          Please refresh the page in a few moments, or check the server logs for diagnostic errors.
        </p>
        <div className="flex gap-4">
          <button onClick={() => window.location.reload()} className="px-8 py-3 bg-brand-red rounded-xl hover:bg-[#ff4d4d] transition-all font-bold">
            Refresh Simulation
          </button>
          <Link to="/submissions" className="px-8 py-3 bg-white/5 border border-white/10 rounded-xl hover:bg-white/10 transition-all font-bold text-white/60">
            Return to History
          </Link>
        </div>
      </div>
    );
  }

  const outcomeScore = simulationRun?.outcomeScore || 0;

  return (
    <div className="max-w-6xl mx-auto space-y-12 pb-32 pt-8">
      {/* Header Navigation */}
      <div className="flex items-center justify-between">
        <Link to="/submissions" className="flex items-center gap-2 text-white/40 hover:text-white transition-colors group">
          <ArrowLeft size={18} className="group-hover:-translate-x-1 transition-transform" /> 
          <span className="font-bold tracking-tight uppercase text-xs">Back to History</span>
        </Link>
        <div className="flex items-center gap-4">
           <span className="text-white/20 text-xs font-mono uppercase">Reference: {submission.id.substring(0, 8)}</span>
           <div className="px-4 py-1.5 rounded-full bg-brand-red/10 border border-brand-red/20 text-brand-red text-[10px] font-bold uppercase tracking-widest">
            {submission.status}
          </div>
        </div>
      </div>

      {/* SECTION 1: PERFORMANCE HERO */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        
        {/* KPI Comparison Table */}
        <div className="lg:col-span-8 space-y-8">
           <div className="space-y-2">
             <h1 className="text-4xl font-bold tracking-tighter">Your Performance Analysis</h1>
             <p className="text-white/40">Results generated by the AX Digital Twin RL Engine</p>
           </div>
           
           {simulationRun && scenario.year0KPIs && (
             <KpiBeforeAfterTable 
               year0={scenario.year0KPIs} 
               candidate={simulationRun.candidateKPIs} 
               optimal={simulationRun.optimalKPIs} 
             />
           )}
        </div>

        {/* Big Outcome Gauge */}
        <div className="lg:col-span-4 bg-dark-card border border-white/5 rounded-3xl p-10 flex flex-col items-center justify-center text-center relative overflow-hidden">
          <div className="absolute top-0 inset-x-0 h-1 bg-gradient-to-r from-transparent via-brand-red to-transparent opacity-20" />
          
          <div className="relative mb-8">
             <svg className="w-56 h-56 transform -rotate-90">
               <circle
                 cx="112" cy="112" r="100"
                 stroke="currentColor" strokeWidth="12" fill="transparent"
                 className="text-white/[0.03]"
               />
               <circle
                 cx="112" cy="112" r="100"
                 stroke="currentColor" strokeWidth="12" fill="transparent"
                 strokeDasharray={628.3}
                 strokeDashoffset={628.3 * (1 - outcomeScore / 100)}
                 className="text-brand-red transition-all duration-1000 ease-out"
                 strokeLinecap="round"
               />
             </svg>
             <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 flex flex-col items-center">
                <span className="text-6xl font-black text-white tracking-tighter">{Math.round(outcomeScore)}</span>
                <span className="text-[10px] font-black uppercase tracking-widest text-brand-red">Percent</span>
             </div>
          </div>

          <div className="space-y-2">
            <h3 className="text-xl font-bold">Outcome Score</h3>
            <p className="text-white/40 text-sm leading-relaxed">
              You captured <b>{Math.round(outcomeScore)}%</b> of the optimal improvement available in this scenario.
            </p>
          </div>

          <div className="mt-8 pt-8 border-t border-white/5 w-full grid grid-cols-2 gap-4">
             <div className="text-left">
                <span className="text-[10px] uppercase font-bold text-white/20 block">Composite Grade</span>
                <span className="text-2xl font-black text-brand-red">{evaluation.grade}</span>
             </div>
             <div className="text-left">
                <span className="text-[10px] uppercase font-bold text-white/20 block">Total weighted score</span>
                <span className="text-2xl font-black text-white/80">{Math.round(evaluation.totalScore)}%</span>
             </div>
          </div>
        </div>
      </div>

      {/* SECTION 2: DECISION TIMELINE */}
      <section className="space-y-12">
         <div className="flex items-center gap-4">
            <div className="h-0.5 w-12 bg-brand-red opacity-50" />
            <h2 className="text-2xl font-bold tracking-tight">Step-by-Step Trajectory Review</h2>
         </div>

         {simulationRun && (
           <DecisionTimeline points={simulationRun.divergencePoints} />
         )}
      </section>

      {/* SECTION 3: RUBRIC & STUDY */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 pt-12 border-t border-white/5">
        
        {/* Rubric Breakdown */}
        <div className="lg:col-span-8 space-y-10">
          <div className="flex items-center gap-3">
             <ClipboardList className="text-brand-red" size={24} />
             <h2 className="text-2xl font-bold tracking-tight">Qualitative Rubric Breakdown</h2>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {[
              { label: 'Semantic Similarity', value: evaluation.semanticScore, weight: '35%' },
              { label: 'Structural Quality', value: evaluation.structureScore, weight: '30%' },
              { label: 'Concept Coverage', value: evaluation.conceptScore, weight: '35%' }
            ].map((metric) => (
              <div key={metric.label} className="bg-[#1f1f1f] border border-white/10 rounded-2xl p-6 space-y-4">
                <div className="flex justify-between items-start">
                  <span className="text-xs font-bold uppercase tracking-widest text-white/20">{metric.label}</span>
                  <span className="text-lg font-black text-white/80">{Math.round(metric.value)}%</span>
                </div>
                <div className="h-1 bg-white/5 rounded-full overflow-hidden">
                  <div 
                    className="h-full bg-brand-red"
                    style={{ width: `${metric.value}%` }}
                  />
                </div>
                <span className="text-[10px] text-white/40 block">Weighting: {metric.weight}</span>
              </div>
            ))}
          </div>

          <div className="bg-dark-card border border-white/5 rounded-3xl p-10 space-y-8">
            <div className="flex items-start gap-4">
               <div className="w-12 h-12 rounded-full bg-brand-red/10 flex items-center justify-center shrink-0">
                  <Brain className="text-brand-red" size={24} />
               </div>
               <div className="space-y-4">
                  <h3 className="text-xl font-bold">Feedback Narrative</h3>
                  <p className="text-white/60 leading-relaxed text-lg font-serif italic">
                    "{evaluation.consultationFeedback}"
                  </p>
               </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-8 pt-8 border-t border-white/5">
               <div className="space-y-4">
                  <h4 className="text-xs font-bold uppercase tracking-[0.2em] text-green-500">Candidate Strengths</h4>
                  <ul className="space-y-3">
                    {evaluation.strengths.map((s, i) => (
                      <li key={i} className="flex gap-3 text-sm text-white/60">
                        <CheckCircle2 size={16} className="text-green-500 shrink-0 mt-0.5" />
                        {s}
                      </li>
                    ))}
                  </ul>
               </div>
               <div className="space-y-4">
                  <h4 className="text-xs font-bold uppercase tracking-[0.2em] text-yellow-500">Critical Improvements</h4>
                  <ul className="space-y-3">
                    {evaluation.improvements.map((s, i) => (
                      <li key={i} className="flex gap-3 text-sm text-white/60">
                        <AlertCircle size={16} className="text-yellow-500 shrink-0 mt-0.5" />
                        {s}
                      </li>
                    ))}
                  </ul>
               </div>
            </div>
          </div>
        </div>

        {/* Study Recommendations sidebar */}
        <div className="lg:col-span-4 space-y-8">
           <div className="bg-brand-red/5 border border-brand-red/20 rounded-3xl p-8 space-y-6">
              <div className="flex items-center gap-3 text-brand-red">
                 <BookOpen size={20} />
                 <h2 className="text-sm font-bold uppercase tracking-widest">Priority Learnings</h2>
              </div>
              <p className="text-xs text-brand-red/60 leading-relaxed uppercase font-bold tracking-tighter">
                Based on your divergence from the optimal trajectory, we recommend prioritizing these concepts:
              </p>
              
              <div className="space-y-4">
                 {evaluation.improvements.slice(0, 3).map((item, i) => (
                   <div key={i} className="flex items-start gap-3 group cursor-pointer">
                      <div className="w-6 h-6 rounded bg-brand-red/10 flex items-center justify-center text-[10px] font-bold text-brand-red group-hover:bg-brand-red group-hover:text-white transition-colors">
                        0{i+1}
                      </div>
                      <span className="text-xs font-bold text-white/70 group-hover:text-white transition-colors leading-tight">
                        {item}
                      </span>
                   </div>
                 ))}
              </div>

              <button className="w-full py-4 bg-brand-red text-white text-[10px] font-bold uppercase tracking-widest rounded-xl flex items-center justify-center gap-2 hover:bg-[#ff4d4d] transition-all">
                Access Training Module <ArrowUpRight size={14} />
              </button>
           </div>

           <div className="bg-[#1f1f1f] border border-white/10 rounded-2xl p-6 space-y-4">
              <span className="text-[10px] font-bold uppercase tracking-widest text-white/20">Ideal Consultation Approach</span>
              <p className="text-xs text-white/40 leading-relaxed line-clamp-4 italic">
                 {evaluation.modelAnswerReveal.substring(0, 200)}...
              </p>
              <button 
                onClick={() => {}} // Could open a modal with full answer
                className="text-brand-red text-[10px] font-bold uppercase tracking-widest flex items-center gap-2 opacity-60 hover:opacity-100"
              >
                Reveal full model approach <ChevronRight size={14} />
              </button>
           </div>
        </div>

      </div>
    </div>
  );
};

export default ResultPage;

